version: '3'
services:
  ffc-mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/
      - ./mongo-seed:/docker-entrypoint-initdb.d
    ports:
      - '27017:27017'
networks:
  ffc_internal:
    external:
      name: ffc_internal